# Generated by Django 4.2.4 on 2023-10-02 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0002_robot_is_availabe_alter_robot_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='robot',
            old_name='is_availabe',
            new_name='is_available',
        ),
    ]
